### ISSUE TITLE
watch-build 之后修改文件报错

### ISSUE THREAD

**Issue by wjy397** [122177638/vue-apiCloud-model-mobile#5]
watch-build之后  loader同步了代码   但是修改代码之后  热更新 就报错
如下：

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\soft\vue\vue-apiCloud2-SPA\apiCloud\page01.f94361dac5de59dbdd83.hot-update.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at getGzippedSize (D:\soft\vue\vue-apiCloud2-SPA\node_modules\@vue\cli-service\lib\commands\build\formatStats.js:44:23)
    at ui.div.assets.map.asset (D:\soft\vue\vue-apiCloud2-SPA\node_modules\@vue\cli-service\lib\commands\build\formatStats.js:63:7)
    at Array.map (<anonymous>)
    at formatStats (D:\soft\vue\vue-apiCloud2-SPA\node_modules\@vue\cli-service\lib\commands\build\formatStats.js:58:12)
    at Watching.webpack [as handler] (D:\soft\vue\vue-apiCloud2-SPA\node_modules\@vue\cli-service\lib\commands\build\index.js:198:13)
    at compiler.hooks.done.callAsync (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Watching.js:98:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\soft\vue\vue-apiCloud2-SPA\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:42:1)
    at Watching._done (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Watching.js:97:28)
    at compiler.emitRecords.err (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Watching.js:72:19)
    at Compiler.emitRecords (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Compiler.js:375:39)
    at compiler.emitAssets.err (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (D:\soft\vue\vue-apiCloud2-SPA\node_modules\webpack\lib\Compiler.js:361:14)
    at _err0 (eval at create (D:\soft\vue\vue-apiCloud2-SPA\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:16:1)
    at callback (D:\soft\vue\vue-apiCloud2-SPA\node_modules\copy-webpack-plugin\dist\index.js:126:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-apiCloud-model-mobile@0.1.0 watch-build: `vue-cli-service build 
--watch --mode development --no-clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-apiCloud-model-mobile@0.1.0 watch-build script.   
npm ERR! This is probably not a problem with npm. There is likely additional 
logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aruis\AppData\Roaming\npm-cache\_logs\2019-11-06T08_43_12_348Z-debug.log

**Comment by 122177638** [comment]
这个是热更新缓存文件错误，我重新升级了项目，并且优化了一部分内容。
